/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/sqjfs6CnpAI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"

export function Tournament() {
  return (
    <div className="w-full max-w-6xl mx-auto px-4 md:px-6 py-12 md:py-16">
      <div className="bg-primary rounded-lg p-6 md:p-8 flex flex-col md:flex-row items-center justify-between mb-8 md:mb-12">
        <div className="space-y-2 md:space-y-3">
          <h2 className="text-2xl md:text-3xl font-bold text-primary-foreground">Annual Gaming Tournament</h2>
          <p className="text-sm md:text-base text-primary-foreground">June 15 - June 20, 2024 | $50,000 Prize Pool</p>
        </div>
        <div className="flex items-center gap-4 mt-4 md:mt-0">
          <Button variant="secondary" size="sm">
            Register Now
          </Button>
          <Button variant="outline" size="sm">
            View Schedule
          </Button>
        </div>
      </div>
      <div className="space-y-6 md:space-y-8">
        <h3 className="text-xl md:text-2xl font-bold">About the Tournament</h3>
        <div className="prose max-w-[800px]">
          <p>
            The Annual Gaming Tournament is a prestigious esports event that brings together the best teams from around
            the world to compete for the coveted championship title and a share of the $50,000 prize pool.
          </p>
          <p>
            Over the course of 6 days, teams will battle it out in a series of intense matches, showcasing their skills
            and strategies in a thrilling display of competitive gaming. With a focus on sportsmanship and camaraderie,
            the tournament promises to be an unforgettable experience for players and spectators alike.
          </p>
        </div>
      </div>
      <div className="mt-8 md:mt-12">
        <h3 className="text-xl md:text-2xl font-bold mb-4 md:mb-6">Participating Teams</h3>
        <div className="overflow-x-auto">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Team</TableHead>
                <TableHead>Rank</TableHead>
                <TableHead>Wins</TableHead>
                <TableHead>Losses</TableHead>
                <TableHead>Region</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell>
                  <div className="flex items-center gap-3">
                    <img
                      src="/placeholder.svg"
                      alt="Team Logo"
                      width={32}
                      height={32}
                      className="rounded-full"
                      style={{ aspectRatio: "32/32", objectFit: "cover" }}
                    />
                    <span>Team Apex</span>
                  </div>
                </TableCell>
                <TableCell>1</TableCell>
                <TableCell>25</TableCell>
                <TableCell>5</TableCell>
                <TableCell>North America</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <div className="flex items-center gap-3">
                    <img
                      src="/placeholder.svg"
                      alt="Team Logo"
                      width={32}
                      height={32}
                      className="rounded-full"
                      style={{ aspectRatio: "32/32", objectFit: "cover" }}
                    />
                    <span>Cyber Wolves</span>
                  </div>
                </TableCell>
                <TableCell>2</TableCell>
                <TableCell>22</TableCell>
                <TableCell>8</TableCell>
                <TableCell>Europe</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <div className="flex items-center gap-3">
                    <img
                      src="/placeholder.svg"
                      alt="Team Logo"
                      width={32}
                      height={32}
                      className="rounded-full"
                      style={{ aspectRatio: "32/32", objectFit: "cover" }}
                    />
                    <span>Pixel Gladiators</span>
                  </div>
                </TableCell>
                <TableCell>3</TableCell>
                <TableCell>20</TableCell>
                <TableCell>10</TableCell>
                <TableCell>Asia</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <div className="flex items-center gap-3">
                    <img
                      src="/placeholder.svg"
                      alt="Team Logo"
                      width={32}
                      height={32}
                      className="rounded-full"
                      style={{ aspectRatio: "32/32", objectFit: "cover" }}
                    />
                    <span>Quantum Esports</span>
                  </div>
                </TableCell>
                <TableCell>4</TableCell>
                <TableCell>18</TableCell>
                <TableCell>12</TableCell>
                <TableCell>South America</TableCell>
              </TableRow>
              <TableRow>
                <TableCell>
                  <div className="flex items-center gap-3">
                    <img
                      src="/placeholder.svg"
                      alt="Team Logo"
                      width={32}
                      height={32}
                      className="rounded-full"
                      style={{ aspectRatio: "32/32", objectFit: "cover" }}
                    />
                    <span>Neon Gladiators</span>
                  </div>
                </TableCell>
                <TableCell>5</TableCell>
                <TableCell>15</TableCell>
                <TableCell>15</TableCell>
                <TableCell>Oceania</TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  )
}
